---
- hosts: gcp
  become: true
  tasks:
  - name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
    apt: 
      name: "{{item.name}}"
      state: present
      install_recommends: no
      update_cache: no
    with_items:
      - { name: docker}
      - { name: nginx}   
   
