---
- name: Copy Artifacts
  hosts: sample_group 
  become: true
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /home/admin/ansible/hosts
      dest: /tmp/hosts
      owner: hr079
      group: hr079
      mode: '0644'
  - name: Copy using inline content
    copy:
      content: '# This file was moved to /etc/other.conf'
      dest: /tmp/hosts
- name: Copy from remote host 
  hosts: sample_group
  become: true
  vars:
    remote_node: 192.168.2.78
  tasks:
  - name: Fetch files from remote host
    fetch:
      src: flow.xml.gz
      dest: /tmp/
- name: Copy to dest host
  hosts: sample_group
  become: true
  tasks:
  - name: copying a file to destination
    copy:
      src: /tmp/flow.xml.gz
      dest: /opt/
