---
- hosts: database
  become: true
  tasks:
  - name: install certain python modules for docker
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
    with_items:
      - { name: docker, version: 2.0.0 }
  - name: ensure docker is started
    service:
      name: docker
      state: started
    notify: 
    - start docker
  handlers:
  - name: start docker
    ansible.builtin.service:
      name: docker
      state: restarted
