---
- hosts: awx_group
  become: true
  tasks:
  - name: Install python pip
    yum:
      name: python-pip
      update_cache: yes
      state: present
  - name: install the latest version of Apache from the testing repo
    yum:
      name: httpd
      state: present
  - name: install mysql
    yum:
      name: mysql
      state: present
  - name: install certain python modules for docker
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: present
    with_items:
      - { name: docker, version: 2.0.0 }
  - name: ensure docker is started
    service:
      name: docker
      state: started
    notify: 
    - start docker
  handlers:
  - name: start docker
    ansible.builtin.service:
      name: docker
      state: restarted
  - name: start mysql
    ansible.builtin.service:
      name: mariadb
      state: restarted
