---
- hosts: gcp
  become: yes
  tasks:
  - name: Install python pip
    yum:
      name: python-pip
      update_cache: yes
      state: absent
  - name: install the latest version of Apache from the testing repo
    yum:
      name: httpd
      state: absent
  - name: install mysql
    yum:
      name: mysql
      state: present
  - name: install certain python modules for docker
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      state: absent
    with_items:
      - { name: docker, version: 2.0.0 }
