---
- hosts: kubernetes
  become: true
  vars_files:
  - secret
  - docker_cred_vault.yaml
  tasks:
  - name: docker login
    command: docker login 192.168.2.82:5000 -u "{{username}}" -p "{{password}}"
  - name: Re-create a test application docker container
    docker_container:
      name: testapplication
      image: 192.168.2.82:5000/gitlab_test
      published_ports: 8081:8080
      pull: yes
      recreate: yes
      state: started
